In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
a = np.random.randn(5)
a

array([-1.63275844, -1.18538012, -0.27880407,  0.82918749, -1.79219348])

In [3]:
a.shape

(5,)

In [4]:
a.T

array([-1.63275844, -1.18538012, -0.27880407,  0.82918749, -1.79219348])

In [5]:
np.dot(a, a.T)

8.048267232859574

In [6]:
b = np.random.randn(5,1)

In [7]:
b

array([[-1.81778341],
       [-0.64318128],
       [-1.69340016],
       [-0.86039771],
       [-0.9638236 ]])

In [8]:
b.shape

(5, 1)

In [9]:
np.dot(b, b.T)

array([[3.30433653, 1.16916426, 3.07823472, 1.56401669, 1.75202256],
       [1.16916426, 0.41368216, 1.08916328, 0.5533917 , 0.6199133 ],
       [3.07823472, 1.08916328, 2.8676041 , 1.45699763, 1.63213904],
       [1.56401669, 0.5533917 , 1.45699763, 0.74028423, 0.82927163],
       [1.75202256, 0.6199133 , 1.63213904, 0.82927163, 0.92895594]])

In [10]:
w = np.arange(5)
w

array([0, 1, 2, 3, 4])

In [11]:
w.shape

(5,)

In [12]:
w1 = w.reshape((5,1))
w1

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [13]:
w1.shape

(5, 1)

In [14]:
w2 = w.reshape([-1,1])
w2

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [15]:
w4 = w[:, np.newaxis]
w4

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [16]:
w4.shape

(5, 1)

In [17]:
w5 = w[np.newaxis,:]
w5

array([[0, 1, 2, 3, 4]])

In [18]:
w5.shape

(1, 5)

In [19]:
t = np.random.rand(5,5)
t

array([[0.14410209, 0.15905536, 0.81793796, 0.710995  , 0.82333362],
       [0.38459632, 0.54129595, 0.23841518, 0.16257491, 0.24427153],
       [0.83746003, 0.08497567, 0.08808271, 0.05764003, 0.25944091],
       [0.91076694, 0.67681961, 0.29783202, 0.03836106, 0.48427984],
       [0.43422497, 0.66725683, 0.00389624, 0.42615327, 0.80542098]])

In [21]:
t.shape


(5, 5)

In [22]:
LA.matrix_rank(t)

5

In [23]:
t.flatten()

array([0.14410209, 0.15905536, 0.81793796, 0.710995  , 0.82333362,
       0.38459632, 0.54129595, 0.23841518, 0.16257491, 0.24427153,
       0.83746003, 0.08497567, 0.08808271, 0.05764003, 0.25944091,
       0.91076694, 0.67681961, 0.29783202, 0.03836106, 0.48427984,
       0.43422497, 0.66725683, 0.00389624, 0.42615327, 0.80542098])

In [24]:
t.flatten().shape

(25,)

In [25]:
LA.matrix_rank(t.flatten())

1

In [26]:
#método flatten() e ravel()#
# o método flatten não altera o valor dentro do array já o ravel altera #
#  
a = np.array([(1, 2, 3, 4), (3, 1, 4, 2)])
print("Original array:\n ")
print(a)
print("Dimension of array-> ", (a.ndim))
print("\nOutput for RAVEL \n")
b = a.ravel()
print(b)
b[0] = 1000
print(b)
print(a)
print("Dimension of array->", (b.ndim))

print("\nOutput for FLATTEN \n")
c = a.flatten()
print(c)
c[0] = 0
print(c)
print(a)
print("Dimension of array-> ", (c.ndim))

Original array:
 
[[1 2 3 4]
 [3 1 4 2]]
Dimension of array->  2

Output for RAVEL 

[1 2 3 4 3 1 4 2]
[1000    2    3    4    3    1    4    2]
[[1000    2    3    4]
 [   3    1    4    2]]
Dimension of array-> 1

Output for FLATTEN 

[1000    2    3    4    3    1    4    2]
[0 2 3 4 3 1 4 2]
[[1000    2    3    4]
 [   3    1    4    2]]
Dimension of array->  1
