In [1]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')


In [2]:
from sklearn.datasets import load_boston
from sklearn.metrics import mean_squared_error

boston_data = load_boston()
boston_data.keys()


dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename', 'data_module'])

In [3]:
type(boston_data)

sklearn.utils.Bunch

In [4]:
boston_data.data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [5]:
# Definindo as entradas dos parametros 
X = boston_data['data']
y = boston_data['target']

In [6]:
print(boston_data['DESCR'])

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [8]:
boston = pd.DataFrame(boston_data['data'], columns = boston_data['feature_names'])

In [9]:
boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [10]:
boston.shape

(506, 13)

In [12]:
boston.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
dtype: int64

In [13]:
pd.DataFrame(y).isnull().sum()

0    0
dtype: int64

In [14]:
boston.describe().T

count        mean         std        min         25%        50%  \
CRIM     506.0    3.613524    8.601545    0.00632    0.082045    0.25651   
ZN       506.0   11.363636   23.322453    0.00000    0.000000    0.00000   
INDUS    506.0   11.136779    6.860353    0.46000    5.190000    9.69000   
CHAS     506.0    0.069170    0.253994    0.00000    0.000000    0.00000   
NOX      506.0    0.554695    0.115878    0.38500    0.449000    0.53800   
RM       506.0    6.284634    0.702617    3.56100    5.885500    6.20850   
AGE      506.0   68.574901   28.148861    2.90000   45.025000   77.50000   
DIS      506.0    3.795043    2.105710    1.12960    2.100175    3.20745   
RAD      506.0    9.549407    8.707259    1.00000    4.000000    5.00000   
TAX      506.0  408.237154  168.537116  187.00000  279.000000  330.00000   
PTRATIO  506.0   18.455534    2.164946   12.60000   17.400000   19.05000   
B        506.0  356.674032   91.294864    0.32000  375.377500  391.44000   
LSTAT    506.0   12.653063    7.141062    1.73000    6.950000   11.36000   

                75%       max  
CRIM       3.677083   88.9762  
ZN        12.500000  100.0000  
INDUS     18.100000   27.7400  
CHAS       0.000000    1.0000  
NOX        0.624000    0.8710  
RM         6.623500    8.7800  
AGE       94.075000  100.0000  
DIS        5.188425   12.1265  
RAD       24.000000   24.0000  
TAX      666.000000  711.0000  
PTRATIO   20.200000   22.0000  
B        396.225000  396.9000  
LSTAT     16.955000   37.9700

## A três tipos API estimador.
* transformers
* classifiers
* regressors
----------------------------------------------------------------
## Escolha uma classe de modelo
* Escolha os hiperparâmetros do modelo
* Organize os dados
* Ajuste o modelo
* Aplique o modelo:
    * aprendizado supervisionado, use o método predict () para prever os rótulos de dados desconhecidos.
    * aprendizagem não supervisionada, use predizer () ou transformar () para inferir propriedades dos dados.
----
## Transformadores
* fit(X): treinar ou ajustar o objeto à matriz de características X
* transform(X): aplica a transformação em X usando quaisquer parâmetros aprendidos
* fit_transform(X): aplica-se a ambos fit(X)e então transform(X).

In [15]:
from sklearn.preprocessing import StandardScaler

# create and fit scaler
scaler = StandardScaler()
scaler.fit(X)

# scale data set
Xt = scaler.transform(X)

# create data frame with results
stats = np.vstack((X.mean(axis=0), X.var(axis=0),
                  Xt.mean(axis=0), Xt.var(axis=0))).T
feature_names = boston_data['feature_names']
columns = ['unscaled mean', 'unscaled variance',
           'scaled mean', 'scaled variance']

df = pd.DataFrame(stats, index=feature_names, columns=columns)


In [16]:
df

unscaled mean  unscaled variance   scaled mean  scaled variance
CRIM          3.613524          73.840360 -8.787437e-17              1.0
ZN           11.363636         542.861840 -6.343191e-16              1.0
INDUS        11.136779          46.971430 -2.682911e-15              1.0
CHAS          0.069170           0.064385  4.701992e-16              1.0
NOX           0.554695           0.013401  2.490322e-15              1.0
RM            6.284634           0.492695 -1.145230e-14              1.0
AGE          68.574901         790.792473 -1.407855e-15              1.0
DIS           3.795043           4.425252  9.210902e-16              1.0
RAD           9.549407          75.666531  5.441409e-16              1.0
TAX         408.237154       28348.623600 -8.868619e-16              1.0
PTRATIO      18.455534           4.677726 -9.205636e-15              1.0
B           356.674032        8318.280421  8.163101e-15              1.0
LSTAT        12.653063          50.893979 -3.370163e-16              1.0

In [17]:
Xs = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
Xs


array([[-500.5],
       [-100.1],
       [   0. ],
       [ 100.1],
       [ 900.9]])

In [20]:
from sklearn import preprocessing
# Create scaler
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

# Scale or Transform the feature
scaled_X = minmax_scale.fit_transform(Xs)

scaled_X


array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [21]:
# Create scaler
minmax_scale = preprocessing.MinMaxScaler(feature_range=(0, 1))

# Scale or Transform the feature
scaled_X = minmax_scale.fit_transform(Xs)

scaled_X


array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [22]:
Xs = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
Xs


array([[-1000.1],
       [ -200.2],
       [  500.5],
       [  600.6],
       [ 9000.9]])

In [23]:
# Create scaler
scaler = preprocessing.StandardScaler()

# Transform the feature
scaled_X = scaler.fit_transform(Xs)

scaled_X

array([[-0.76058269],
       [-0.54177196],
       [-0.35009716],
       [-0.32271504],
       [ 1.97516685]])

In [24]:
# Create scaler
robust_scaler = preprocessing.RobustScaler()

# Transform feature
robust_scaler.fit_transform(Xs)


array([[-1.87387612],
       [-0.875     ],
       [ 0.        ],
       [ 0.125     ],
       [10.61488511]])

In [25]:
# Create feature matrix
Xs = np.array([[0.5, 0.5], [1.1, 3.4], [1.5, 20.2], [1.63, 34.4], [10.9, 3.3]])
Xs

array([[ 0.5 ,  0.5 ],
       [ 1.1 ,  3.4 ],
       [ 1.5 , 20.2 ],
       [ 1.63, 34.4 ],
       [10.9 ,  3.3 ]])

In [26]:
# Transform feature with l1 norm
preprocessing.Normalizer(norm="l1").fit_transform(Xs)


array([[0.5       , 0.5       ],
       [0.24444444, 0.75555556],
       [0.06912442, 0.93087558],
       [0.04524008, 0.95475992],
       [0.76760563, 0.23239437]])

In [27]:
# Transform feature with l2 norm
preprocessing.Normalizer(norm="l2").fit_transform(Xs)


array([[0.70710678, 0.70710678],
       [0.30782029, 0.95144452],
       [0.07405353, 0.99725427],
       [0.04733062, 0.99887928],
       [0.95709822, 0.28976368]])

In [28]:
# Transform feature with max norm
preprocessing.Normalizer(norm="max").fit_transform(Xs)


array([[1.        , 1.        ],
       [0.32352941, 1.        ],
       [0.07425743, 1.        ],
       [0.04738372, 1.        ],
       [1.        , 0.30275229]])

### Cenario 1
* scaled_dataset = (dataset - mean_dataset) / stdev_dataset
* train, test = split (scaled_dataset)

### Cenario 2

* train, test = split (dataset)
* scaled_train = (train - mean_train) / stdev_train
* scaled_test = (test - mean_test) / stdev_test

### Cenario 3
* scaled_train = (train - mean_train) / stdev_train
* scaled_test = (test - mean_train) / stdev_train

In [29]:
from sklearn.linear_model import LinearRegression, Lasso

# create model and train/fit
model = LinearRegression()
model.fit(X, y)  # training

# predict label values on X
y_pred = model.predict(X)  # predicting

print(y_pred[:10])
print(f'R^2: {model.score(X, y):0.4}')


[30.00384338 25.02556238 30.56759672 28.60703649 27.94352423 25.25628446
 23.00180827 19.53598843 11.52363685 18.92026211]
R^2: 0.7406


In [30]:
np.around(model.coef_, 1)


array([ -0.1,   0. ,   0. ,   2.7, -17.8,   3.8,   0. ,  -1.5,   0.3,
        -0. ,  -1. ,   0. ,  -0.5])

In [31]:
from sklearn.ensemble import GradientBoostingRegressor

# create model and train/fit
model = GradientBoostingRegressor()
model.fit(X, y)

# predict label values on X
y_pred = model.predict(X)

print(y_pred[:10])
print(f'R-Square: {model.score(X, y):0.4}')


[25.90772604 21.96320179 33.92712155 34.14528061 35.41267912 26.7925396
 21.48031031 20.87839556 16.95411564 18.45898255]
R-Square: 0.9761


In [32]:
from sklearn.pipeline import Pipeline

# list of tuples
pipe = Pipeline([('scaler', StandardScaler()),
                ('regressor', LinearRegression())])


In [33]:
pipe.named_steps


{'scaler': StandardScaler(), 'regressor': LinearRegression()}

In [35]:
# fit/train model
pipe.fit(X, y)

# predict labels
y_pred = pipe.predict(X)

print(y_pred[:10])
print(f'R^2: {pipe.score(X, y):0.4}')


[30.00384338 25.02556238 30.56759672 28.60703649 27.94352423 25.25628446
 23.00180827 19.53598843 11.52363685 18.92026211]
R^2: 0.7406


In [36]:
from sklearn.pipeline import FeatureUnion
from sklearn.decomposition import PCA
from sklearn.feature_selection import f_regression, SelectKBest

#Pipeline([]) -- is the list of tuples

pca_pipe = Pipeline([('scaler', StandardScaler()),
                    ('dim_red', PCA(n_components=4))])
union = FeatureUnion(
    [('pca_pipe', pca_pipe), ('selector', SelectKBest(f_regression, k=2))])

# predictor is the last step
pipe = Pipeline([('union', union), ('regressor', LinearRegression())])
pipe.fit(X, y)

print(f'Number of features in the original dataset: {X.shape[-1]}')
print(f'Number of features in the new dataset: {union.transform(X).shape[-1]}')
print(f'R-Square: {pipe.score(X, y):0.4}')


Number of features in the original dataset: 13
Number of features in the new dataset: 6
R-Square: 0.6931
